name: 03 - Python Script Workflow

on:
  push:
    branches: [ main ] 
  schedule: 
    - cron: '0/10 * * * 1-5'
  workflow_dispatch:



jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.11 # Install the python version needed

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests lxml pandas

      - name: Execute Python script # Run the run.py to get the latest data
        run: |
          python realtimeforex.py
          #python Pivot_points.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated realtimeforex.txt file"
          git push
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
